### Teste da rota GET
GET http://localhost:3000/api/auth/test
Content-Type: application/json

### Teste da rota POST Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "tessste@teste.com",
  "password": "H@usmano12",
  "name": "natanaelhlacerda"
  
}

### Teste da rota POST de login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "hausmano"
  
}

### Teste da rota GET do perfil do usuário
GET http://localhost:3000/api/user/profile
Content-Type: application/json

### Teste da rota GET do perfil do usuário com token
GET http://localhost:3000/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2MDRiOTA1LTJmMDktNGRlNi1hMTNiLTMxZGRjZmE4MDE3MSIsIm5hbWUiOiJuYXRhbmFlbGhsYWNlcmRhIiwiaWF0IjoxNzYxNzU3MTkwLCJleHAiOjE3NjIzNjE5OTB9.5zKs8unPu76qWlhs9419yYb43HHaNE9wJP_tIgveNEw"
